[package]
name = "chat-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["ws"] }
futures-util = { version = "0.3.31", features = ["sink", "std"] }
iced = { version = "0.14.0", features = ["tokio", "sipper"] }
tokio = { version = "1.49.0", features = ["full"] }
tokio-tungstenite = "0.28.0"
dotenvy = "0.15"
sea-orm = { version = "2.0.0-rc", features = [ "sqlx-postgres", "runtime-tokio-native-tls", "macros" ] }
async-tungstenite = { version = "0.32.1", features = [ "tokio-runtime" ] }
rkyv = { version = "0.8.15", features = ["uuid-1", "alloc"] }
bytes = "1.11.1"

[dependencies.uuid]
version = "1.19.0"
features = [
    "v4",
]
